// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: service.proto

package coverforge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoverForge_Welcome_FullMethodName = "/coverforge.CoverForge/Welcome"
	CoverForge_Health_FullMethodName  = "/coverforge.CoverForge/Health"
)

// CoverForgeClient is the client API for CoverForge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoverForgeClient interface {
	Welcome(ctx context.Context, in *WelcomeRequest, opts ...grpc.CallOption) (*WelcomeResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type coverForgeClient struct {
	cc grpc.ClientConnInterface
}

func NewCoverForgeClient(cc grpc.ClientConnInterface) CoverForgeClient {
	return &coverForgeClient{cc}
}

func (c *coverForgeClient) Welcome(ctx context.Context, in *WelcomeRequest, opts ...grpc.CallOption) (*WelcomeResponse, error) {
	out := new(WelcomeResponse)
	err := c.cc.Invoke(ctx, CoverForge_Welcome_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coverForgeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CoverForge_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoverForgeServer is the server API for CoverForge service.
// All implementations must embed UnimplementedCoverForgeServer
// for forward compatibility
type CoverForgeServer interface {
	Welcome(context.Context, *WelcomeRequest) (*WelcomeResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedCoverForgeServer()
}

// UnimplementedCoverForgeServer must be embedded to have forward compatible implementations.
type UnimplementedCoverForgeServer struct {
}

func (UnimplementedCoverForgeServer) Welcome(context.Context, *WelcomeRequest) (*WelcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Welcome not implemented")
}
func (UnimplementedCoverForgeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCoverForgeServer) mustEmbedUnimplementedCoverForgeServer() {}

// UnsafeCoverForgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoverForgeServer will
// result in compilation errors.
type UnsafeCoverForgeServer interface {
	mustEmbedUnimplementedCoverForgeServer()
}

func RegisterCoverForgeServer(s grpc.ServiceRegistrar, srv CoverForgeServer) {
	s.RegisterService(&CoverForge_ServiceDesc, srv)
}

func _CoverForge_Welcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoverForgeServer).Welcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoverForge_Welcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoverForgeServer).Welcome(ctx, req.(*WelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoverForge_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoverForgeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoverForge_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoverForgeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoverForge_ServiceDesc is the grpc.ServiceDesc for CoverForge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoverForge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coverforge.CoverForge",
	HandlerType: (*CoverForgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Welcome",
			Handler:    _CoverForge_Welcome_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CoverForge_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
