# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-ip.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crpc-ip.proto\x12\x08trueauth\"%\n\x15\x41llowIPAddressRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\")\n\x16\x41llowIPAddressResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB#Z!github.com/sirjager/rpcs/trueauthb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_ip_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!github.com/sirjager/rpcs/trueauth'
  _ALLOWIPADDRESSREQUEST._serialized_start=26
  _ALLOWIPADDRESSREQUEST._serialized_end=63
  _ALLOWIPADDRESSRESPONSE._serialized_start=65
  _ALLOWIPADDRESSRESPONSE._serialized_end=106
# @@protoc_insertion_point(module_scope)
