# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-signout.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rpc-signout.proto\x12\x08trueauth\"\"\n\x0eSignoutRequest\x12\x10\n\x08sessions\x18\x01 \x03(\t\"\"\n\x0fSignoutResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB#Z!github.com/sirjager/rpcs/trueauthb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_signout_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!github.com/sirjager/rpcs/trueauth'
  _SIGNOUTREQUEST._serialized_start=31
  _SIGNOUTREQUEST._serialized_end=65
  _SIGNOUTRESPONSE._serialized_start=67
  _SIGNOUTRESPONSE._serialized_end=101
# @@protoc_insertion_point(module_scope)
