# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-forgot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rpc-forgot.proto\x12\x08trueauth\"&\n\x15\x46orgotPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\")\n\x16\x46orgotPasswordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"d\n\x14ResetPasswordRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\x12\x19\n\x11logout_everywhere\x18\x04 \x01(\x08\"(\n\x15ResetPasswordResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB#Z!github.com/sirjager/rpcs/trueauthb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_forgot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!github.com/sirjager/rpcs/trueauth'
  _FORGOTPASSWORDREQUEST._serialized_start=30
  _FORGOTPASSWORDREQUEST._serialized_end=68
  _FORGOTPASSWORDRESPONSE._serialized_start=70
  _FORGOTPASSWORDRESPONSE._serialized_end=111
  _RESETPASSWORDREQUEST._serialized_start=113
  _RESETPASSWORDREQUEST._serialized_end=213
  _RESETPASSWORDRESPONSE._serialized_start=215
  _RESETPASSWORDRESPONSE._serialized_end=255
# @@protoc_insertion_point(module_scope)
