# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-verify.authentication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from user import authentication_pb2 as user_dot_authentication__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1frpc-verify.authentication.proto\x12\x0e\x61uthentication\x1a\x19user.authentication.proto\"/\n-AuthenticationRequestEmailVerificationRequest\"A\n.AuthenticationRequestEmailVerificationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n AuthenticationVerifyEmailRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"U\n!AuthenticationVerifyEmailResponse\x12\x30\n\x04user\x18\x01 \x01(\x0b\x32\".authentication.AuthenticationUserB)Z\'github.com/sirjager/rpcs/authenticationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_verify.authentication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/sirjager/rpcs/authentication'
  _AUTHENTICATIONREQUESTEMAILVERIFICATIONREQUEST._serialized_start=78
  _AUTHENTICATIONREQUESTEMAILVERIFICATIONREQUEST._serialized_end=125
  _AUTHENTICATIONREQUESTEMAILVERIFICATIONRESPONSE._serialized_start=127
  _AUTHENTICATIONREQUESTEMAILVERIFICATIONRESPONSE._serialized_end=192
  _AUTHENTICATIONVERIFYEMAILREQUEST._serialized_start=194
  _AUTHENTICATIONVERIFYEMAILREQUEST._serialized_end=242
  _AUTHENTICATIONVERIFYEMAILRESPONSE._serialized_start=244
  _AUTHENTICATIONVERIFYEMAILRESPONSE._serialized_end=329
# @@protoc_insertion_point(module_scope)
