# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-signup.auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from user import auth_pb2 as user_dot_auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rpc-signup.auth.proto\x12\x04\x61uth\x1a\x0fuser.auth.proto\"k\n\x11\x41uthSignupRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x11\n\tfirstname\x18\x04 \x01(\t\x12\x10\n\x08lastname\x18\x05 \x01(\t\"2\n\x12\x41uthSignupResponse\x12\x1c\n\x04user\x18\x01 \x01(\x0b\x32\x0e.auth.AuthUserB\x1fZ\x1dgithub.com/sirjager/rpcs/authb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_signup.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035github.com/sirjager/rpcs/auth'
  _AUTHSIGNUPREQUEST._serialized_start=48
  _AUTHSIGNUPREQUEST._serialized_end=155
  _AUTHSIGNUPRESPONSE._serialized_start=157
  _AUTHSIGNUPRESPONSE._serialized_end=207
# @@protoc_insertion_point(module_scope)
