# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-send.emails.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc-send.emails.proto',
  package='emails',
  syntax='proto3',
  serialized_options=_b('Z\037github.com/sirjager/rpcs/emails'),
  serialized_pb=_b('\n\x15rpc-send.emails.proto\x12\x06\x65mails\"X\n\x15\x45mailsSendMailRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\")\n\x16\x45mailsSendMailResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB!Z\x1fgithub.com/sirjager/rpcs/emailsb\x06proto3')
)




_EMAILSSENDMAILREQUEST = _descriptor.Descriptor(
  name='EmailsSendMailRequest',
  full_name='emails.EmailsSendMailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='emails.EmailsSendMailRequest.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='emails.EmailsSendMailRequest.receiver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='emails.EmailsSendMailRequest.subject', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='emails.EmailsSendMailRequest.body', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=121,
)


_EMAILSSENDMAILRESPONSE = _descriptor.Descriptor(
  name='EmailsSendMailResponse',
  full_name='emails.EmailsSendMailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='emails.EmailsSendMailResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['EmailsSendMailRequest'] = _EMAILSSENDMAILREQUEST
DESCRIPTOR.message_types_by_name['EmailsSendMailResponse'] = _EMAILSSENDMAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailsSendMailRequest = _reflection.GeneratedProtocolMessageType('EmailsSendMailRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMAILSSENDMAILREQUEST,
  __module__ = 'rpc_send.emails_pb2'
  # @@protoc_insertion_point(class_scope:emails.EmailsSendMailRequest)
  ))
_sym_db.RegisterMessage(EmailsSendMailRequest)

EmailsSendMailResponse = _reflection.GeneratedProtocolMessageType('EmailsSendMailResponse', (_message.Message,), dict(
  DESCRIPTOR = _EMAILSSENDMAILRESPONSE,
  __module__ = 'rpc_send.emails_pb2'
  # @@protoc_insertion_point(class_scope:emails.EmailsSendMailResponse)
  ))
_sym_db.RegisterMessage(EmailsSendMailResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
