// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: rpc-groups.whisper_nation.proto

package whisper_nation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhisperNationListGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhisperNationListGroupsRequest) Reset() {
	*x = WhisperNationListGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_groups_whisper_nation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhisperNationListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhisperNationListGroupsRequest) ProtoMessage() {}

func (x *WhisperNationListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_groups_whisper_nation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhisperNationListGroupsRequest.ProtoReflect.Descriptor instead.
func (*WhisperNationListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_groups_whisper_nation_proto_rawDescGZIP(), []int{0}
}

type WhisperNationListGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*WhisperNationGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *WhisperNationListGroupsResponse) Reset() {
	*x = WhisperNationListGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_groups_whisper_nation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhisperNationListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhisperNationListGroupsResponse) ProtoMessage() {}

func (x *WhisperNationListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_groups_whisper_nation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhisperNationListGroupsResponse.ProtoReflect.Descriptor instead.
func (*WhisperNationListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_groups_whisper_nation_proto_rawDescGZIP(), []int{1}
}

func (x *WhisperNationListGroupsResponse) GetGroups() []*WhisperNationGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type WhisperNationCreateGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *WhisperNationCreateGroupRequest) Reset() {
	*x = WhisperNationCreateGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_groups_whisper_nation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhisperNationCreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhisperNationCreateGroupRequest) ProtoMessage() {}

func (x *WhisperNationCreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_groups_whisper_nation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhisperNationCreateGroupRequest.ProtoReflect.Descriptor instead.
func (*WhisperNationCreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_groups_whisper_nation_proto_rawDescGZIP(), []int{2}
}

func (x *WhisperNationCreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WhisperNationCreateGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group *WhisperNationGroup `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *WhisperNationCreateGroupResponse) Reset() {
	*x = WhisperNationCreateGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_groups_whisper_nation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhisperNationCreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhisperNationCreateGroupResponse) ProtoMessage() {}

func (x *WhisperNationCreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_groups_whisper_nation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhisperNationCreateGroupResponse.ProtoReflect.Descriptor instead.
func (*WhisperNationCreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_groups_whisper_nation_proto_rawDescGZIP(), []int{3}
}

func (x *WhisperNationCreateGroupResponse) GetGroup() *WhisperNationGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type WhisperNationJoinGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *WhisperNationJoinGroupRequest) Reset() {
	*x = WhisperNationJoinGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_groups_whisper_nation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhisperNationJoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhisperNationJoinGroupRequest) ProtoMessage() {}

func (x *WhisperNationJoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_groups_whisper_nation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhisperNationJoinGroupRequest.ProtoReflect.Descriptor instead.
func (*WhisperNationJoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_groups_whisper_nation_proto_rawDescGZIP(), []int{4}
}

func (x *WhisperNationJoinGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *WhisperNationJoinGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WhisperNationJoinGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WhisperNationJoinGroupResponse) Reset() {
	*x = WhisperNationJoinGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_groups_whisper_nation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhisperNationJoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhisperNationJoinGroupResponse) ProtoMessage() {}

func (x *WhisperNationJoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_groups_whisper_nation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhisperNationJoinGroupResponse.ProtoReflect.Descriptor instead.
func (*WhisperNationJoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_groups_whisper_nation_proto_rawDescGZIP(), []int{5}
}

func (x *WhisperNationJoinGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_groups_whisper_nation_proto protoreflect.FileDescriptor

var file_rpc_groups_whisper_nation_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x2e, 0x77, 0x68, 0x69,
	0x73, 0x70, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x77, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x14, 0x77, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x1e, 0x57, 0x68, 0x69, 0x73, 0x70,
	0x65, 0x72, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x1f, 0x57, 0x68, 0x69,
	0x73, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x06,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x77,
	0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x68,
	0x69, 0x73, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x35, 0x0a, 0x1f, 0x57, 0x68, 0x69, 0x73,
	0x70, 0x65, 0x72, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x5c, 0x0a, 0x20, 0x57, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x77, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x53, 0x0a,
	0x1d, 0x57, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x6f,
	0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x3a, 0x0a, 0x1e, 0x57, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x29,
	0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x72,
	0x6a, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x77, 0x68, 0x69, 0x73, 0x70,
	0x65, 0x72, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rpc_groups_whisper_nation_proto_rawDescOnce sync.Once
	file_rpc_groups_whisper_nation_proto_rawDescData = file_rpc_groups_whisper_nation_proto_rawDesc
)

func file_rpc_groups_whisper_nation_proto_rawDescGZIP() []byte {
	file_rpc_groups_whisper_nation_proto_rawDescOnce.Do(func() {
		file_rpc_groups_whisper_nation_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_groups_whisper_nation_proto_rawDescData)
	})
	return file_rpc_groups_whisper_nation_proto_rawDescData
}

var file_rpc_groups_whisper_nation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_groups_whisper_nation_proto_goTypes = []interface{}{
	(*WhisperNationListGroupsRequest)(nil),   // 0: whisper_nation.WhisperNationListGroupsRequest
	(*WhisperNationListGroupsResponse)(nil),  // 1: whisper_nation.WhisperNationListGroupsResponse
	(*WhisperNationCreateGroupRequest)(nil),  // 2: whisper_nation.WhisperNationCreateGroupRequest
	(*WhisperNationCreateGroupResponse)(nil), // 3: whisper_nation.WhisperNationCreateGroupResponse
	(*WhisperNationJoinGroupRequest)(nil),    // 4: whisper_nation.WhisperNationJoinGroupRequest
	(*WhisperNationJoinGroupResponse)(nil),   // 5: whisper_nation.WhisperNationJoinGroupResponse
	(*WhisperNationGroup)(nil),               // 6: whisper_nation.WhisperNationGroup
}
var file_rpc_groups_whisper_nation_proto_depIdxs = []int32{
	6, // 0: whisper_nation.WhisperNationListGroupsResponse.groups:type_name -> whisper_nation.WhisperNationGroup
	6, // 1: whisper_nation.WhisperNationCreateGroupResponse.group:type_name -> whisper_nation.WhisperNationGroup
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_groups_whisper_nation_proto_init() }
func file_rpc_groups_whisper_nation_proto_init() {
	if File_rpc_groups_whisper_nation_proto != nil {
		return
	}
	file_whisper_nation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_groups_whisper_nation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhisperNationListGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_groups_whisper_nation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhisperNationListGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_groups_whisper_nation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhisperNationCreateGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_groups_whisper_nation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhisperNationCreateGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_groups_whisper_nation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhisperNationJoinGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_groups_whisper_nation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhisperNationJoinGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_groups_whisper_nation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_groups_whisper_nation_proto_goTypes,
		DependencyIndexes: file_rpc_groups_whisper_nation_proto_depIdxs,
		MessageInfos:      file_rpc_groups_whisper_nation_proto_msgTypes,
	}.Build()
	File_rpc_groups_whisper_nation_proto = out.File
	file_rpc_groups_whisper_nation_proto_rawDesc = nil
	file_rpc_groups_whisper_nation_proto_goTypes = nil
	file_rpc_groups_whisper_nation_proto_depIdxs = nil
}
