# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-users.auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from user import auth_pb2 as user_dot_auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14rpc-users.auth.proto\x12\x04\x61uth\x1a\x0fuser.auth.proto\"/\n\x10\x41uthUsersRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\"2\n\x11\x41uthUsersResponse\x12\x1d\n\x05users\x18\x01 \x03(\x0b\x32\x0e.auth.AuthUser\"#\n\x0f\x41uthUserRequest\x12\x10\n\x08identity\x18\x01 \x01(\t\"0\n\x10\x41uthUserResponse\x12\x1c\n\x04user\x18\x01 \x01(\x0b\x32\x0e.auth.AuthUserB\x1fZ\x1dgithub.com/sirjager/rpcs/authb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_users.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035github.com/sirjager/rpcs/auth'
  _AUTHUSERSREQUEST._serialized_start=47
  _AUTHUSERSREQUEST._serialized_end=94
  _AUTHUSERSRESPONSE._serialized_start=96
  _AUTHUSERSRESPONSE._serialized_end=146
  _AUTHUSERREQUEST._serialized_start=148
  _AUTHUSERREQUEST._serialized_end=183
  _AUTHUSERRESPONSE._serialized_start=185
  _AUTHUSERRESPONSE._serialized_end=233
# @@protoc_insertion_point(module_scope)
