# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-delete.auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rpc-delete.auth.proto\x12\x04\x61uth\"\x1a\n\x18\x41uthDeleteAccountRequest\",\n\x19\x41uthDeleteAccountResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB\x1fZ\x1dgithub.com/sirjager/rpcs/authb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_delete.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035github.com/sirjager/rpcs/auth'
  _AUTHDELETEACCOUNTREQUEST._serialized_start=31
  _AUTHDELETEACCOUNTREQUEST._serialized_end=57
  _AUTHDELETEACCOUNTRESPONSE._serialized_start=59
  _AUTHDELETEACCOUNTRESPONSE._serialized_end=103
# @@protoc_insertion_point(module_scope)
