# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-members.whisper_nation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import whisper_nation_pb2 as whisper__nation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n rpc-members.whisper_nation.proto\x12\x0ewhisper_nation\x1a\x14whisper_nation.proto\"8\n$WhisperNationListGroupMembersRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\"]\n%WhisperNationListGroupMembersResponse\x12\x34\n\x07members\x18\x01 \x03(\x0b\x32#.whisper_nation.WhisperNationMemberB)Z\'github.com/sirjager/rpcs/whisper_nationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_members.whisper_nation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/sirjager/rpcs/whisper_nation'
  _WHISPERNATIONLISTGROUPMEMBERSREQUEST._serialized_start=74
  _WHISPERNATIONLISTGROUPMEMBERSREQUEST._serialized_end=130
  _WHISPERNATIONLISTGROUPMEMBERSRESPONSE._serialized_start=132
  _WHISPERNATIONLISTGROUPMEMBERSRESPONSE._serialized_end=225
# @@protoc_insertion_point(module_scope)
