/**
 * @fileoverview gRPC-Web generated client stub for trueauth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var protoc$gen$openapiv2_options_annotations_pb = require('./protoc-gen-openapiv2/options/annotations_pb.js')

var rpc$welcome_pb = require('./rpc-welcome_pb.js')

var rpc$health_pb = require('./rpc-health_pb.js')

var rpc$register_pb = require('./rpc-register_pb.js')

var rpc$login_pb = require('./rpc-login_pb.js')

var rpc$verify_pb = require('./rpc-verify_pb.js')

var rpc$refresh_pb = require('./rpc-refresh_pb.js')

var rpc$logout_pb = require('./rpc-logout_pb.js')

var rpc$recovery_pb = require('./rpc-recovery_pb.js')

var rpc$update_pb = require('./rpc-update_pb.js')

var rpc$delete_pb = require('./rpc-delete_pb.js')

var rpc$allowip_pb = require('./rpc-allowip_pb.js')

var rpc$users_pb = require('./rpc-users_pb.js')
const proto = {};
proto.trueauth = require('./service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.trueauth.TrueAuthClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.trueauth.TrueAuthPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.WelcomeRequest,
 *   !proto.trueauth.WelcomeResponse>}
 */
const methodDescriptor_TrueAuth_Welcome = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Welcome',
  grpc.web.MethodType.UNARY,
  rpc$welcome_pb.WelcomeRequest,
  rpc$welcome_pb.WelcomeResponse,
  /**
   * @param {!proto.trueauth.WelcomeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$welcome_pb.WelcomeResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.WelcomeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.WelcomeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.WelcomeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.welcome =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Welcome',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Welcome,
      callback);
};


/**
 * @param {!proto.trueauth.WelcomeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.WelcomeResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.welcome =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Welcome',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Welcome);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.HealthRequest,
 *   !proto.trueauth.HealthResponse>}
 */
const methodDescriptor_TrueAuth_Health = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Health',
  grpc.web.MethodType.UNARY,
  rpc$health_pb.HealthRequest,
  rpc$health_pb.HealthResponse,
  /**
   * @param {!proto.trueauth.HealthRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$health_pb.HealthResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.HealthRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.HealthResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.HealthResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.health =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Health',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Health,
      callback);
};


/**
 * @param {!proto.trueauth.HealthRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.HealthResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.health =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Health',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Health);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.RegisterRequest,
 *   !proto.trueauth.RegisterResponse>}
 */
const methodDescriptor_TrueAuth_Register = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Register',
  grpc.web.MethodType.UNARY,
  rpc$register_pb.RegisterRequest,
  rpc$register_pb.RegisterResponse,
  /**
   * @param {!proto.trueauth.RegisterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$register_pb.RegisterResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.RegisterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.RegisterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Register',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Register,
      callback);
};


/**
 * @param {!proto.trueauth.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.RegisterResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Register',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.LoginRequest,
 *   !proto.trueauth.LoginResponse>}
 */
const methodDescriptor_TrueAuth_Login = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Login',
  grpc.web.MethodType.UNARY,
  rpc$login_pb.LoginRequest,
  rpc$login_pb.LoginResponse,
  /**
   * @param {!proto.trueauth.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$login_pb.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Login',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Login,
      callback);
};


/**
 * @param {!proto.trueauth.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Login',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.VerifyRequest,
 *   !proto.trueauth.VerifyResponse>}
 */
const methodDescriptor_TrueAuth_Verify = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Verify',
  grpc.web.MethodType.UNARY,
  rpc$verify_pb.VerifyRequest,
  rpc$verify_pb.VerifyResponse,
  /**
   * @param {!proto.trueauth.VerifyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$verify_pb.VerifyResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.VerifyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.VerifyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.VerifyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.verify =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Verify',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Verify,
      callback);
};


/**
 * @param {!proto.trueauth.VerifyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.VerifyResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.verify =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Verify',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Verify);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.LogoutRequest,
 *   !proto.trueauth.LogoutResponse>}
 */
const methodDescriptor_TrueAuth_Logout = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Logout',
  grpc.web.MethodType.UNARY,
  rpc$logout_pb.LogoutRequest,
  rpc$logout_pb.LogoutResponse,
  /**
   * @param {!proto.trueauth.LogoutRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$logout_pb.LogoutResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.LogoutRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.LogoutResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.LogoutResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.logout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Logout',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Logout,
      callback);
};


/**
 * @param {!proto.trueauth.LogoutRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.LogoutResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.logout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Logout',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Logout);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.RefreshRequest,
 *   !proto.trueauth.RefreshResponse>}
 */
const methodDescriptor_TrueAuth_Refresh = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Refresh',
  grpc.web.MethodType.UNARY,
  rpc$refresh_pb.RefreshRequest,
  rpc$refresh_pb.RefreshResponse,
  /**
   * @param {!proto.trueauth.RefreshRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$refresh_pb.RefreshResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.RefreshRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.RefreshResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.RefreshResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.refresh =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Refresh',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Refresh,
      callback);
};


/**
 * @param {!proto.trueauth.RefreshRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.RefreshResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.refresh =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Refresh',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Refresh);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.RecoveryRequest,
 *   !proto.trueauth.RecoveryResponse>}
 */
const methodDescriptor_TrueAuth_Recovery = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Recovery',
  grpc.web.MethodType.UNARY,
  rpc$recovery_pb.RecoveryRequest,
  rpc$recovery_pb.RecoveryResponse,
  /**
   * @param {!proto.trueauth.RecoveryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$recovery_pb.RecoveryResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.RecoveryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.RecoveryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.RecoveryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.recovery =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Recovery',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Recovery,
      callback);
};


/**
 * @param {!proto.trueauth.RecoveryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.RecoveryResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.recovery =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Recovery',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Recovery);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.DeleteRequest,
 *   !proto.trueauth.DeleteResponse>}
 */
const methodDescriptor_TrueAuth_Delete = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Delete',
  grpc.web.MethodType.UNARY,
  rpc$delete_pb.DeleteRequest,
  rpc$delete_pb.DeleteResponse,
  /**
   * @param {!proto.trueauth.DeleteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$delete_pb.DeleteResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.DeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.DeleteResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.DeleteResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Delete',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Delete,
      callback);
};


/**
 * @param {!proto.trueauth.DeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.DeleteResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Delete',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.UpdateRequest,
 *   !proto.trueauth.UpdateResponse>}
 */
const methodDescriptor_TrueAuth_Update = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/Update',
  grpc.web.MethodType.UNARY,
  rpc$update_pb.UpdateRequest,
  rpc$update_pb.UpdateResponse,
  /**
   * @param {!proto.trueauth.UpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$update_pb.UpdateResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.UpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.UpdateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.UpdateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/Update',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Update,
      callback);
};


/**
 * @param {!proto.trueauth.UpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.UpdateResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/Update',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.AllowIPRequest,
 *   !proto.trueauth.AllowIPResponse>}
 */
const methodDescriptor_TrueAuth_AllowIP = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/AllowIP',
  grpc.web.MethodType.UNARY,
  rpc$allowip_pb.AllowIPRequest,
  rpc$allowip_pb.AllowIPResponse,
  /**
   * @param {!proto.trueauth.AllowIPRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$allowip_pb.AllowIPResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.AllowIPRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.AllowIPResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.AllowIPResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.allowIP =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/AllowIP',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_AllowIP,
      callback);
};


/**
 * @param {!proto.trueauth.AllowIPRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.AllowIPResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.allowIP =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/AllowIP',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_AllowIP);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trueauth.UserRequest,
 *   !proto.trueauth.UserResponse>}
 */
const methodDescriptor_TrueAuth_User = new grpc.web.MethodDescriptor(
  '/trueauth.TrueAuth/User',
  grpc.web.MethodType.UNARY,
  rpc$users_pb.UserRequest,
  rpc$users_pb.UserResponse,
  /**
   * @param {!proto.trueauth.UserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rpc$users_pb.UserResponse.deserializeBinary
);


/**
 * @param {!proto.trueauth.UserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trueauth.UserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trueauth.UserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trueauth.TrueAuthClient.prototype.user =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trueauth.TrueAuth/User',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_User,
      callback);
};


/**
 * @param {!proto.trueauth.UserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trueauth.UserResponse>}
 *     Promise that resolves to the response
 */
proto.trueauth.TrueAuthPromiseClient.prototype.user =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trueauth.TrueAuth/User',
      request,
      metadata || {},
      methodDescriptor_TrueAuth_User);
};


module.exports = proto.trueauth;

