# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.utils.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
from rpc_health import utils_pb2 as rpc__health_dot_utils__pb2
from rpc_welcome import utils_pb2 as rpc__welcome_dot_utils__pb2
from rpc_useragent import utils_pb2 as rpc__useragent_dot_utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13service.utils.proto\x12\x05utils\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x16rpc-health.utils.proto\x1a\x17rpc-welcome.utils.proto\x1a\x19rpc-useragent.utils.proto2\xb1\x06\n\x05Utils\x12\x7f\n\x0cUtilsWelcome\x12\x1a.utils.UtilsWelcomeRequest\x1a\x1b.utils.UtilsWelcomeResponse\"6\x82\xd3\xe4\x93\x02\x03\x12\x01/\x92\x41*\n\x06System\x12\x0fWelcome Message\x1a\x0fWelcome Message\x12{\n\x0bUtilsHealth\x12\x19.utils.UtilsHealthRequest\x1a\x1a.utils.UtilsHealthResponse\"5\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/health\x92\x41 \n\x06System\x12\nApi Health\x1a\nApi Health\x12\x93\x01\n\x0fUtilsUserAgents\x12\x1d.utils.UtilsUserAgentsRequest\x1a\x1e.utils.UtilsUserAgentsResponse\"A\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/user-agents\x92\x41\'\n\x0bUser Agents\x12\x0bUser Agents\x1a\x0bUser Agents\x12\xce\x01\n\x13UtilsUserAgentsPool\x12!.utils.UtilsUserAgentsPoolRequest\x1a\".utils.UtilsUserAgentsPoolResponse\"p\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/user-agents/{pool}\x92\x41O\n\x0bUser Agents\x12\x1fUser Agents From Requested Pool\x1a\x1fUser Agents From Requested Pool\x12\xc2\x01\n\x18UtilsUserAgentsPoolNames\x12&.utils.UtilsUserAgentsPoolNamesRequest\x1a\'.utils.UtilsUserAgentsPoolNamesResponse\"U\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/user-agents/pools\x92\x41\x35\n\x0bUser Agents\x12\x12User Agents Groups\x1a\x12User Agents GroupsBgZ\x1egithub.com/sirjager/rpcs/utils\x92\x41\x44\x12\x42\n\tUtils Api\"0\n\x08SirJager\x12$https://github.com/sirjager/go_utils2\x03\x30.1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service.utils_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\036github.com/sirjager/rpcs/utils\222AD\022B\n\tUtils Api\"0\n\010SirJager\022$https://github.com/sirjager/go_utils2\0030.1'
  _UTILS.methods_by_name['UtilsWelcome']._options = None
  _UTILS.methods_by_name['UtilsWelcome']._serialized_options = b'\202\323\344\223\002\003\022\001/\222A*\n\006System\022\017Welcome Message\032\017Welcome Message'
  _UTILS.methods_by_name['UtilsHealth']._options = None
  _UTILS.methods_by_name['UtilsHealth']._serialized_options = b'\202\323\344\223\002\014\022\n/v1/health\222A \n\006System\022\nApi Health\032\nApi Health'
  _UTILS.methods_by_name['UtilsUserAgents']._options = None
  _UTILS.methods_by_name['UtilsUserAgents']._serialized_options = b'\202\323\344\223\002\021\022\017/v1/user-agents\222A\'\n\013User Agents\022\013User Agents\032\013User Agents'
  _UTILS.methods_by_name['UtilsUserAgentsPool']._options = None
  _UTILS.methods_by_name['UtilsUserAgentsPool']._serialized_options = b'\202\323\344\223\002\030\022\026/v1/user-agents/{pool}\222AO\n\013User Agents\022\037User Agents From Requested Pool\032\037User Agents From Requested Pool'
  _UTILS.methods_by_name['UtilsUserAgentsPoolNames']._options = None
  _UTILS.methods_by_name['UtilsUserAgentsPoolNames']._serialized_options = b'\202\323\344\223\002\027\022\025/v1/user-agents/pools\222A5\n\013User Agents\022\022User Agents Groups\032\022User Agents Groups'
  _UTILS._serialized_start=185
  _UTILS._serialized_end=1002
# @@protoc_insertion_point(module_scope)
