# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-forgot.authentication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1frpc-forgot.authentication.proto\x12\x0e\x61uthentication\"4\n#AuthenticationForgotPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"7\n$AuthenticationForgotPasswordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"r\n\"AuthenticationResetPasswordRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\x12\x19\n\x11logout_everywhere\x18\x04 \x01(\x08\"6\n#AuthenticationResetPasswordResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB)Z\'github.com/sirjager/rpcs/authenticationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_forgot.authentication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/sirjager/rpcs/authentication'
  _AUTHENTICATIONFORGOTPASSWORDREQUEST._serialized_start=51
  _AUTHENTICATIONFORGOTPASSWORDREQUEST._serialized_end=103
  _AUTHENTICATIONFORGOTPASSWORDRESPONSE._serialized_start=105
  _AUTHENTICATIONFORGOTPASSWORDRESPONSE._serialized_end=160
  _AUTHENTICATIONRESETPASSWORDREQUEST._serialized_start=162
  _AUTHENTICATIONRESETPASSWORDREQUEST._serialized_end=276
  _AUTHENTICATIONRESETPASSWORDRESPONSE._serialized_start=278
  _AUTHENTICATIONRESETPASSWORDRESPONSE._serialized_end=332
# @@protoc_insertion_point(module_scope)
