# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-signout.authentication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n rpc-signout.authentication.proto\x12\x0e\x61uthentication\"0\n\x1c\x41uthenticationSignoutRequest\x12\x10\n\x08sessions\x18\x01 \x03(\t\"0\n\x1d\x41uthenticationSignoutResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB)Z\'github.com/sirjager/rpcs/authenticationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_signout.authentication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/sirjager/rpcs/authentication'
  _AUTHENTICATIONSIGNOUTREQUEST._serialized_start=52
  _AUTHENTICATIONSIGNOUTREQUEST._serialized_end=100
  _AUTHENTICATIONSIGNOUTRESPONSE._serialized_start=102
  _AUTHENTICATIONSIGNOUTRESPONSE._serialized_end=150
# @@protoc_insertion_point(module_scope)
