# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-groups.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import whisper_nation_pb2 as whisper__nation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rpc-groups.proto\x12\x0ewhisper_nation\x1a\x14whisper_nation.proto\"/\n\x1fWhisperNationCreateGroupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"U\n WhisperNationCreateGroupResponse\x12\x31\n\x05group\x18\x01 \x01(\x0b\x32\".whisper_nation.WhisperNationGroup\" \n\x1eWhisperNationListGroupsRequest\"U\n\x1fWhisperNationListGroupsResponse\x12\x32\n\x06groups\x18\x01 \x03(\x0b\x32\".whisper_nation.WhisperNationGroup\"8\n$WhisperNationListGroupMembersRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\"]\n%WhisperNationListGroupMembersResponse\x12\x34\n\x07members\x18\x01 \x03(\x0b\x32#.whisper_nation.WhisperNationMemberB)Z\'github.com/sirjager/rpcs/whisper_nationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_groups_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/sirjager/rpcs/whisper_nation'
  _WHISPERNATIONCREATEGROUPREQUEST._serialized_start=58
  _WHISPERNATIONCREATEGROUPREQUEST._serialized_end=105
  _WHISPERNATIONCREATEGROUPRESPONSE._serialized_start=107
  _WHISPERNATIONCREATEGROUPRESPONSE._serialized_end=192
  _WHISPERNATIONLISTGROUPSREQUEST._serialized_start=194
  _WHISPERNATIONLISTGROUPSREQUEST._serialized_end=226
  _WHISPERNATIONLISTGROUPSRESPONSE._serialized_start=228
  _WHISPERNATIONLISTGROUPSRESPONSE._serialized_end=313
  _WHISPERNATIONLISTGROUPMEMBERSREQUEST._serialized_start=315
  _WHISPERNATIONLISTGROUPMEMBERSREQUEST._serialized_end=371
  _WHISPERNATIONLISTGROUPMEMBERSRESPONSE._serialized_start=373
  _WHISPERNATIONLISTGROUPMEMBERSRESPONSE._serialized_end=466
# @@protoc_insertion_point(module_scope)
