# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-welcome.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rpc-welcome.proto\x12\x0ewhisper_nation\"\x1d\n\x1bWhisperNationWelcomeRequest\"/\n\x1cWhisperNationWelcomeResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB)Z\'github.com/sirjager/rpcs/whisper_nationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_welcome_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/sirjager/rpcs/whisper_nation'
  _WHISPERNATIONWELCOMEREQUEST._serialized_start=37
  _WHISPERNATIONWELCOMEREQUEST._serialized_end=66
  _WHISPERNATIONWELCOMERESPONSE._serialized_start=68
  _WHISPERNATIONWELCOMERESPONSE._serialized_end=115
# @@protoc_insertion_point(module_scope)
