# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-verify.auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from user import auth_pb2 as user_dot_auth__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc-verify.auth.proto',
  package='auth',
  syntax='proto3',
  serialized_options=_b('Z\035github.com/sirjager/rpcs/auth'),
  serialized_pb=_b('\n\x15rpc-verify.auth.proto\x12\x04\x61uth\x1a\x0fuser.auth.proto\"%\n#AuthRequestEmailVerificationRequest\"7\n$AuthRequestEmailVerificationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x16\x41uthVerifyEmailRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"7\n\x17\x41uthVerifyEmailResponse\x12\x1c\n\x04user\x18\x01 \x01(\x0b\x32\x0e.auth.AuthUserB\x1fZ\x1dgithub.com/sirjager/rpcs/authb\x06proto3')
  ,
  dependencies=[user_dot_auth__pb2.DESCRIPTOR,])




_AUTHREQUESTEMAILVERIFICATIONREQUEST = _descriptor.Descriptor(
  name='AuthRequestEmailVerificationRequest',
  full_name='auth.AuthRequestEmailVerificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=85,
)


_AUTHREQUESTEMAILVERIFICATIONRESPONSE = _descriptor.Descriptor(
  name='AuthRequestEmailVerificationResponse',
  full_name='auth.AuthRequestEmailVerificationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='auth.AuthRequestEmailVerificationResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=142,
)


_AUTHVERIFYEMAILREQUEST = _descriptor.Descriptor(
  name='AuthVerifyEmailRequest',
  full_name='auth.AuthVerifyEmailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='auth.AuthVerifyEmailRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=182,
)


_AUTHVERIFYEMAILRESPONSE = _descriptor.Descriptor(
  name='AuthVerifyEmailResponse',
  full_name='auth.AuthVerifyEmailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='auth.AuthVerifyEmailResponse.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=239,
)

_AUTHVERIFYEMAILRESPONSE.fields_by_name['user'].message_type = user_dot_auth__pb2._AUTHUSER
DESCRIPTOR.message_types_by_name['AuthRequestEmailVerificationRequest'] = _AUTHREQUESTEMAILVERIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['AuthRequestEmailVerificationResponse'] = _AUTHREQUESTEMAILVERIFICATIONRESPONSE
DESCRIPTOR.message_types_by_name['AuthVerifyEmailRequest'] = _AUTHVERIFYEMAILREQUEST
DESCRIPTOR.message_types_by_name['AuthVerifyEmailResponse'] = _AUTHVERIFYEMAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthRequestEmailVerificationRequest = _reflection.GeneratedProtocolMessageType('AuthRequestEmailVerificationRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHREQUESTEMAILVERIFICATIONREQUEST,
  __module__ = 'rpc_verify.auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.AuthRequestEmailVerificationRequest)
  ))
_sym_db.RegisterMessage(AuthRequestEmailVerificationRequest)

AuthRequestEmailVerificationResponse = _reflection.GeneratedProtocolMessageType('AuthRequestEmailVerificationResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHREQUESTEMAILVERIFICATIONRESPONSE,
  __module__ = 'rpc_verify.auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.AuthRequestEmailVerificationResponse)
  ))
_sym_db.RegisterMessage(AuthRequestEmailVerificationResponse)

AuthVerifyEmailRequest = _reflection.GeneratedProtocolMessageType('AuthVerifyEmailRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHVERIFYEMAILREQUEST,
  __module__ = 'rpc_verify.auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.AuthVerifyEmailRequest)
  ))
_sym_db.RegisterMessage(AuthVerifyEmailRequest)

AuthVerifyEmailResponse = _reflection.GeneratedProtocolMessageType('AuthVerifyEmailResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHVERIFYEMAILRESPONSE,
  __module__ = 'rpc_verify.auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.AuthVerifyEmailResponse)
  ))
_sym_db.RegisterMessage(AuthVerifyEmailResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
