# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-verify.auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from user import auth_pb2 as user_dot_auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rpc-verify.auth.proto\x12\x04\x61uth\x1a\x0fuser.auth.proto\"%\n#AuthRequestEmailVerificationRequest\"7\n$AuthRequestEmailVerificationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x16\x41uthVerifyEmailRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"7\n\x17\x41uthVerifyEmailResponse\x12\x1c\n\x04user\x18\x01 \x01(\x0b\x32\x0e.auth.AuthUserB\x1fZ\x1dgithub.com/sirjager/rpcs/authb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_verify.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035github.com/sirjager/rpcs/auth'
  _AUTHREQUESTEMAILVERIFICATIONREQUEST._serialized_start=48
  _AUTHREQUESTEMAILVERIFICATIONREQUEST._serialized_end=85
  _AUTHREQUESTEMAILVERIFICATIONRESPONSE._serialized_start=87
  _AUTHREQUESTEMAILVERIFICATIONRESPONSE._serialized_end=142
  _AUTHVERIFYEMAILREQUEST._serialized_start=144
  _AUTHVERIFYEMAILREQUEST._serialized_end=182
  _AUTHVERIFYEMAILRESPONSE._serialized_start=184
  _AUTHVERIFYEMAILRESPONSE._serialized_end=239
# @@protoc_insertion_point(module_scope)
