# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.emails.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
from rpc_health import emails_pb2 as rpc__health_dot_emails__pb2
from rpc_send import emails_pb2 as rpc__send_dot_emails__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.emails.proto',
  package='emails',
  syntax='proto3',
  serialized_options=_b('Z\037github.com/sirjager/rpcs/emails\222A?\022=\n\nEmails Api\"*\n\013Ankur Kumar\022\033https://github.com/sirjager2\0030.2'),
  serialized_pb=_b('\n\x14service.emails.proto\x12\x06\x65mails\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17rpc-health.emails.proto\x1a\x15rpc-send.emails.proto2\xca\x02\n\x06\x45mails\x12\xa3\x01\n\x0c\x45mailsHealth\x12\x1b.emails.EmailsHealthRequest\x1a\x1c.emails.EmailsHealthResponse\"X\x82\xd3\xe4\x93\x02\t\x12\x07/health\x92\x41\x46\n\x06System\x12\nApi Health\x1a\x30use this route to check if api is working or not\x12\x99\x01\n\x0e\x45mailsSendMail\x12\x1d.emails.EmailsSendMailRequest\x1a\x1e.emails.EmailsSendMailResponse\"H\x82\xd3\xe4\x93\x02\r\"\x08/v1/send:\x01*\x92\x41\x32\n\x06\x45mails\x12\nSend Email\x1a\x1cuse this route to send emailBcZ\x1fgithub.com/sirjager/rpcs/emails\x92\x41?\x12=\n\nEmails Api\"*\n\x0b\x41nkur Kumar\x12\x1bhttps://github.com/sirjager2\x03\x30.2b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,protoc__gen__openapiv2_dot_options_dot_annotations__pb2.DESCRIPTOR,rpc__health_dot_emails__pb2.DESCRIPTOR,rpc__send_dot_emails__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_EMAILS = _descriptor.ServiceDescriptor(
  name='Emails',
  full_name='emails.Emails',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=159,
  serialized_end=489,
  methods=[
  _descriptor.MethodDescriptor(
    name='EmailsHealth',
    full_name='emails.Emails.EmailsHealth',
    index=0,
    containing_service=None,
    input_type=rpc__health_dot_emails__pb2._EMAILSHEALTHREQUEST,
    output_type=rpc__health_dot_emails__pb2._EMAILSHEALTHRESPONSE,
    serialized_options=_b('\202\323\344\223\002\t\022\007/health\222AF\n\006System\022\nApi Health\0320use this route to check if api is working or not'),
  ),
  _descriptor.MethodDescriptor(
    name='EmailsSendMail',
    full_name='emails.Emails.EmailsSendMail',
    index=1,
    containing_service=None,
    input_type=rpc__send_dot_emails__pb2._EMAILSSENDMAILREQUEST,
    output_type=rpc__send_dot_emails__pb2._EMAILSSENDMAILRESPONSE,
    serialized_options=_b('\202\323\344\223\002\r\"\010/v1/send:\001*\222A2\n\006Emails\022\nSend Email\032\034use this route to send email'),
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAILS)

DESCRIPTOR.services_by_name['Emails'] = _EMAILS

# @@protoc_insertion_point(module_scope)
