# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-health.whisper_nation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1frpc-health.whisper_nation.proto\x12\x0ewhisper_nation\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x1c\n\x1aWhisperNationHealthRequest\"\xc4\x01\n\x1bWhisperNationHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06unsafe\x18\x02 \x01(\x08\x12)\n\x06uptime\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12+\n\x07started\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB)Z\'github.com/sirjager/rpcs/whisper_nationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_health.whisper_nation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/sirjager/rpcs/whisper_nation'
  _WHISPERNATIONHEALTHREQUEST._serialized_start=116
  _WHISPERNATIONHEALTHREQUEST._serialized_end=144
  _WHISPERNATIONHEALTHRESPONSE._serialized_start=147
  _WHISPERNATIONHEALTHRESPONSE._serialized_end=343
# @@protoc_insertion_point(module_scope)
