# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-groups.whisper_nation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import whisper_nation_pb2 as whisper__nation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1frpc-groups.whisper_nation.proto\x12\x0ewhisper_nation\x1a\x14whisper_nation.proto\" \n\x1eWhisperNationListGroupsRequest\"U\n\x1fWhisperNationListGroupsResponse\x12\x32\n\x06groups\x18\x01 \x03(\x0b\x32\".whisper_nation.WhisperNationGroup\"/\n\x1fWhisperNationCreateGroupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"U\n WhisperNationCreateGroupResponse\x12\x31\n\x05group\x18\x01 \x01(\x0b\x32\".whisper_nation.WhisperNationGroup\"B\n\x1dWhisperNationJoinGroupRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"1\n\x1eWhisperNationJoinGroupResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB)Z\'github.com/sirjager/rpcs/whisper_nationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_groups.whisper_nation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/sirjager/rpcs/whisper_nation'
  _WHISPERNATIONLISTGROUPSREQUEST._serialized_start=73
  _WHISPERNATIONLISTGROUPSREQUEST._serialized_end=105
  _WHISPERNATIONLISTGROUPSRESPONSE._serialized_start=107
  _WHISPERNATIONLISTGROUPSRESPONSE._serialized_end=192
  _WHISPERNATIONCREATEGROUPREQUEST._serialized_start=194
  _WHISPERNATIONCREATEGROUPREQUEST._serialized_end=241
  _WHISPERNATIONCREATEGROUPRESPONSE._serialized_start=243
  _WHISPERNATIONCREATEGROUPRESPONSE._serialized_end=328
  _WHISPERNATIONJOINGROUPREQUEST._serialized_start=330
  _WHISPERNATIONJOINGROUPREQUEST._serialized_end=396
  _WHISPERNATIONJOINGROUPRESPONSE._serialized_start=398
  _WHISPERNATIONJOINGROUPRESPONSE._serialized_end=447
# @@protoc_insertion_point(module_scope)
