// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: rpc-verify.authentication.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationRequestEmailVerificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthenticationRequestEmailVerificationRequest) Reset() {
	*x = AuthenticationRequestEmailVerificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_verify_authentication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationRequestEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequestEmailVerificationRequest) ProtoMessage() {}

func (x *AuthenticationRequestEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_verify_authentication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequestEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequestEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_verify_authentication_proto_rawDescGZIP(), []int{0}
}

type AuthenticationRequestEmailVerificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AuthenticationRequestEmailVerificationResponse) Reset() {
	*x = AuthenticationRequestEmailVerificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_verify_authentication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationRequestEmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequestEmailVerificationResponse) ProtoMessage() {}

func (x *AuthenticationRequestEmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_verify_authentication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequestEmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationRequestEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_verify_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationRequestEmailVerificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuthenticationVerifyEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AuthenticationVerifyEmailRequest) Reset() {
	*x = AuthenticationVerifyEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_verify_authentication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationVerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationVerifyEmailRequest) ProtoMessage() {}

func (x *AuthenticationVerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_verify_authentication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationVerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationVerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_rpc_verify_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticationVerifyEmailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AuthenticationVerifyEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *AuthenticationUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AuthenticationVerifyEmailResponse) Reset() {
	*x = AuthenticationVerifyEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_verify_authentication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationVerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationVerifyEmailResponse) ProtoMessage() {}

func (x *AuthenticationVerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_verify_authentication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationVerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationVerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_rpc_verify_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticationVerifyEmailResponse) GetUser() *AuthenticationUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_rpc_verify_authentication_proto protoreflect.FileDescriptor

var file_rpc_verify_authentication_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x70, 0x63, 0x2d, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x19, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x2d,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x20, 0x41, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x5b, 0x0a, 0x21, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x29,
	0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x72,
	0x6a, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rpc_verify_authentication_proto_rawDescOnce sync.Once
	file_rpc_verify_authentication_proto_rawDescData = file_rpc_verify_authentication_proto_rawDesc
)

func file_rpc_verify_authentication_proto_rawDescGZIP() []byte {
	file_rpc_verify_authentication_proto_rawDescOnce.Do(func() {
		file_rpc_verify_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_verify_authentication_proto_rawDescData)
	})
	return file_rpc_verify_authentication_proto_rawDescData
}

var file_rpc_verify_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_verify_authentication_proto_goTypes = []interface{}{
	(*AuthenticationRequestEmailVerificationRequest)(nil),  // 0: authentication.AuthenticationRequestEmailVerificationRequest
	(*AuthenticationRequestEmailVerificationResponse)(nil), // 1: authentication.AuthenticationRequestEmailVerificationResponse
	(*AuthenticationVerifyEmailRequest)(nil),               // 2: authentication.AuthenticationVerifyEmailRequest
	(*AuthenticationVerifyEmailResponse)(nil),              // 3: authentication.AuthenticationVerifyEmailResponse
	(*AuthenticationUser)(nil),                             // 4: authentication.AuthenticationUser
}
var file_rpc_verify_authentication_proto_depIdxs = []int32{
	4, // 0: authentication.AuthenticationVerifyEmailResponse.user:type_name -> authentication.AuthenticationUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_verify_authentication_proto_init() }
func file_rpc_verify_authentication_proto_init() {
	if File_rpc_verify_authentication_proto != nil {
		return
	}
	file_user_authentication_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_verify_authentication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationRequestEmailVerificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_verify_authentication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationRequestEmailVerificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_verify_authentication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationVerifyEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_verify_authentication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationVerifyEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_verify_authentication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_verify_authentication_proto_goTypes,
		DependencyIndexes: file_rpc_verify_authentication_proto_depIdxs,
		MessageInfos:      file_rpc_verify_authentication_proto_msgTypes,
	}.Build()
	File_rpc_verify_authentication_proto = out.File
	file_rpc_verify_authentication_proto_rawDesc = nil
	file_rpc_verify_authentication_proto_goTypes = nil
	file_rpc_verify_authentication_proto_depIdxs = nil
}
