// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: rpc-users.authentication.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page  int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *AuthenticationUsersRequest) Reset() {
	*x = AuthenticationUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_users_authentication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationUsersRequest) ProtoMessage() {}

func (x *AuthenticationUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_users_authentication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationUsersRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationUsersRequest) Descriptor() ([]byte, []int) {
	return file_rpc_users_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AuthenticationUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type AuthenticationUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*AuthenticationUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *AuthenticationUsersResponse) Reset() {
	*x = AuthenticationUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_users_authentication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationUsersResponse) ProtoMessage() {}

func (x *AuthenticationUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_users_authentication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationUsersResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationUsersResponse) Descriptor() ([]byte, []int) {
	return file_rpc_users_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationUsersResponse) GetUsers() []*AuthenticationUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type AuthenticationUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *AuthenticationUserRequest) Reset() {
	*x = AuthenticationUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_users_authentication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationUserRequest) ProtoMessage() {}

func (x *AuthenticationUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_users_authentication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_users_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticationUserRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type AuthenticationUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *AuthenticationUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AuthenticationUserResponse) Reset() {
	*x = AuthenticationUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_users_authentication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationUserResponse) ProtoMessage() {}

func (x *AuthenticationUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_users_authentication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationUserResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationUserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_users_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticationUserResponse) GetUser() *AuthenticationUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_rpc_users_authentication_proto protoreflect.FileDescriptor

var file_rpc_users_authentication_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x70, 0x63, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x19, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x1a, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x22, 0x57, 0x0a, 0x1b, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x37, 0x0a, 0x19,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x54, 0x0a, 0x1a, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x72, 0x6a, 0x61, 0x67,
	0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_users_authentication_proto_rawDescOnce sync.Once
	file_rpc_users_authentication_proto_rawDescData = file_rpc_users_authentication_proto_rawDesc
)

func file_rpc_users_authentication_proto_rawDescGZIP() []byte {
	file_rpc_users_authentication_proto_rawDescOnce.Do(func() {
		file_rpc_users_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_users_authentication_proto_rawDescData)
	})
	return file_rpc_users_authentication_proto_rawDescData
}

var file_rpc_users_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_users_authentication_proto_goTypes = []interface{}{
	(*AuthenticationUsersRequest)(nil),  // 0: authentication.AuthenticationUsersRequest
	(*AuthenticationUsersResponse)(nil), // 1: authentication.AuthenticationUsersResponse
	(*AuthenticationUserRequest)(nil),   // 2: authentication.AuthenticationUserRequest
	(*AuthenticationUserResponse)(nil),  // 3: authentication.AuthenticationUserResponse
	(*AuthenticationUser)(nil),          // 4: authentication.AuthenticationUser
}
var file_rpc_users_authentication_proto_depIdxs = []int32{
	4, // 0: authentication.AuthenticationUsersResponse.users:type_name -> authentication.AuthenticationUser
	4, // 1: authentication.AuthenticationUserResponse.user:type_name -> authentication.AuthenticationUser
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_users_authentication_proto_init() }
func file_rpc_users_authentication_proto_init() {
	if File_rpc_users_authentication_proto != nil {
		return
	}
	file_user_authentication_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_users_authentication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_users_authentication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_users_authentication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_users_authentication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_users_authentication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_users_authentication_proto_goTypes,
		DependencyIndexes: file_rpc_users_authentication_proto_depIdxs,
		MessageInfos:      file_rpc_users_authentication_proto_msgTypes,
	}.Build()
	File_rpc_users_authentication_proto = out.File
	file_rpc_users_authentication_proto_rawDesc = nil
	file_rpc_users_authentication_proto_goTypes = nil
	file_rpc_users_authentication_proto_depIdxs = nil
}
