// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: service.emails.proto

package emails

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Emails_EmailsHealth_FullMethodName   = "/emails.Emails/EmailsHealth"
	Emails_EmailsSendMail_FullMethodName = "/emails.Emails/EmailsSendMail"
)

// EmailsClient is the client API for Emails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailsClient interface {
	EmailsHealth(ctx context.Context, in *EmailsHealthRequest, opts ...grpc.CallOption) (*EmailsHealthResponse, error)
	// ------------------------------------------------------------ SendEmail
	EmailsSendMail(ctx context.Context, in *EmailsSendMailRequest, opts ...grpc.CallOption) (*EmailsSendMailResponse, error)
}

type emailsClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailsClient(cc grpc.ClientConnInterface) EmailsClient {
	return &emailsClient{cc}
}

func (c *emailsClient) EmailsHealth(ctx context.Context, in *EmailsHealthRequest, opts ...grpc.CallOption) (*EmailsHealthResponse, error) {
	out := new(EmailsHealthResponse)
	err := c.cc.Invoke(ctx, Emails_EmailsHealth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailsClient) EmailsSendMail(ctx context.Context, in *EmailsSendMailRequest, opts ...grpc.CallOption) (*EmailsSendMailResponse, error) {
	out := new(EmailsSendMailResponse)
	err := c.cc.Invoke(ctx, Emails_EmailsSendMail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailsServer is the server API for Emails service.
// All implementations must embed UnimplementedEmailsServer
// for forward compatibility
type EmailsServer interface {
	EmailsHealth(context.Context, *EmailsHealthRequest) (*EmailsHealthResponse, error)
	// ------------------------------------------------------------ SendEmail
	EmailsSendMail(context.Context, *EmailsSendMailRequest) (*EmailsSendMailResponse, error)
	mustEmbedUnimplementedEmailsServer()
}

// UnimplementedEmailsServer must be embedded to have forward compatible implementations.
type UnimplementedEmailsServer struct {
}

func (UnimplementedEmailsServer) EmailsHealth(context.Context, *EmailsHealthRequest) (*EmailsHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailsHealth not implemented")
}
func (UnimplementedEmailsServer) EmailsSendMail(context.Context, *EmailsSendMailRequest) (*EmailsSendMailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailsSendMail not implemented")
}
func (UnimplementedEmailsServer) mustEmbedUnimplementedEmailsServer() {}

// UnsafeEmailsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailsServer will
// result in compilation errors.
type UnsafeEmailsServer interface {
	mustEmbedUnimplementedEmailsServer()
}

func RegisterEmailsServer(s grpc.ServiceRegistrar, srv EmailsServer) {
	s.RegisterService(&Emails_ServiceDesc, srv)
}

func _Emails_EmailsHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailsHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailsServer).EmailsHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Emails_EmailsHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailsServer).EmailsHealth(ctx, req.(*EmailsHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emails_EmailsSendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailsSendMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailsServer).EmailsSendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Emails_EmailsSendMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailsServer).EmailsSendMail(ctx, req.(*EmailsSendMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Emails_ServiceDesc is the grpc.ServiceDesc for Emails service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Emails_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emails.Emails",
	HandlerType: (*EmailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmailsHealth",
			Handler:    _Emails_EmailsHealth_Handler,
		},
		{
			MethodName: "EmailsSendMail",
			Handler:    _Emails_EmailsSendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.emails.proto",
}
