# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-useragent.utils.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc-useragent.utils.proto',
  package='utils',
  syntax='proto3',
  serialized_options=_b('Z\036github.com/sirjager/rpcs/utils'),
  serialized_pb=_b('\n\x19rpc-useragent.utils.proto\x12\x05utils\"*\n\x0eUtilsUserAgent\x12\n\n\x02ua\x18\x01 \x01(\t\x12\x0c\n\x04info\x18\x02 \x01(\t\"v\n\x13UtilsUserAgentGroup\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x06\x61gents\x18\x02 \x03(\x0b\x32\x15.utils.UtilsUserAgent\x12*\n\x06groups\x18\x03 \x03(\x0b\x32\x1a.utils.UtilsUserAgentGroup\"\x18\n\x16UtilsUserAgentsRequest\"*\n\x17UtilsUserAgentsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n UtilsUserAgentsGroupNamesRequest\"3\n!UtilsUserAgentsGroupNamesResponse\x12\x0e\n\x06groups\x18\x01 \x03(\t\"-\n\x1cUtilsUserAgentsGroupsRequest\x12\r\n\x05group\x18\x01 \x01(\t\"J\n\x1dUtilsUserAgentsGroupsResponse\x12)\n\x05group\x18\x01 \x01(\x0b\x32\x1a.utils.UtilsUserAgentGroupB Z\x1egithub.com/sirjager/rpcs/utilsb\x06proto3')
)




_UTILSUSERAGENT = _descriptor.Descriptor(
  name='UtilsUserAgent',
  full_name='utils.UtilsUserAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ua', full_name='utils.UtilsUserAgent.ua', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='utils.UtilsUserAgent.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=78,
)


_UTILSUSERAGENTGROUP = _descriptor.Descriptor(
  name='UtilsUserAgentGroup',
  full_name='utils.UtilsUserAgentGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='utils.UtilsUserAgentGroup.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agents', full_name='utils.UtilsUserAgentGroup.agents', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groups', full_name='utils.UtilsUserAgentGroup.groups', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=198,
)


_UTILSUSERAGENTSREQUEST = _descriptor.Descriptor(
  name='UtilsUserAgentsRequest',
  full_name='utils.UtilsUserAgentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=224,
)


_UTILSUSERAGENTSRESPONSE = _descriptor.Descriptor(
  name='UtilsUserAgentsResponse',
  full_name='utils.UtilsUserAgentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='utils.UtilsUserAgentsResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=268,
)


_UTILSUSERAGENTSGROUPNAMESREQUEST = _descriptor.Descriptor(
  name='UtilsUserAgentsGroupNamesRequest',
  full_name='utils.UtilsUserAgentsGroupNamesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=304,
)


_UTILSUSERAGENTSGROUPNAMESRESPONSE = _descriptor.Descriptor(
  name='UtilsUserAgentsGroupNamesResponse',
  full_name='utils.UtilsUserAgentsGroupNamesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='utils.UtilsUserAgentsGroupNamesResponse.groups', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=357,
)


_UTILSUSERAGENTSGROUPSREQUEST = _descriptor.Descriptor(
  name='UtilsUserAgentsGroupsRequest',
  full_name='utils.UtilsUserAgentsGroupsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='utils.UtilsUserAgentsGroupsRequest.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=404,
)


_UTILSUSERAGENTSGROUPSRESPONSE = _descriptor.Descriptor(
  name='UtilsUserAgentsGroupsResponse',
  full_name='utils.UtilsUserAgentsGroupsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='utils.UtilsUserAgentsGroupsResponse.group', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=480,
)

_UTILSUSERAGENTGROUP.fields_by_name['agents'].message_type = _UTILSUSERAGENT
_UTILSUSERAGENTGROUP.fields_by_name['groups'].message_type = _UTILSUSERAGENTGROUP
_UTILSUSERAGENTSGROUPSRESPONSE.fields_by_name['group'].message_type = _UTILSUSERAGENTGROUP
DESCRIPTOR.message_types_by_name['UtilsUserAgent'] = _UTILSUSERAGENT
DESCRIPTOR.message_types_by_name['UtilsUserAgentGroup'] = _UTILSUSERAGENTGROUP
DESCRIPTOR.message_types_by_name['UtilsUserAgentsRequest'] = _UTILSUSERAGENTSREQUEST
DESCRIPTOR.message_types_by_name['UtilsUserAgentsResponse'] = _UTILSUSERAGENTSRESPONSE
DESCRIPTOR.message_types_by_name['UtilsUserAgentsGroupNamesRequest'] = _UTILSUSERAGENTSGROUPNAMESREQUEST
DESCRIPTOR.message_types_by_name['UtilsUserAgentsGroupNamesResponse'] = _UTILSUSERAGENTSGROUPNAMESRESPONSE
DESCRIPTOR.message_types_by_name['UtilsUserAgentsGroupsRequest'] = _UTILSUSERAGENTSGROUPSREQUEST
DESCRIPTOR.message_types_by_name['UtilsUserAgentsGroupsResponse'] = _UTILSUSERAGENTSGROUPSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UtilsUserAgent = _reflection.GeneratedProtocolMessageType('UtilsUserAgent', (_message.Message,), dict(
  DESCRIPTOR = _UTILSUSERAGENT,
  __module__ = 'rpc_useragent.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsUserAgent)
  ))
_sym_db.RegisterMessage(UtilsUserAgent)

UtilsUserAgentGroup = _reflection.GeneratedProtocolMessageType('UtilsUserAgentGroup', (_message.Message,), dict(
  DESCRIPTOR = _UTILSUSERAGENTGROUP,
  __module__ = 'rpc_useragent.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsUserAgentGroup)
  ))
_sym_db.RegisterMessage(UtilsUserAgentGroup)

UtilsUserAgentsRequest = _reflection.GeneratedProtocolMessageType('UtilsUserAgentsRequest', (_message.Message,), dict(
  DESCRIPTOR = _UTILSUSERAGENTSREQUEST,
  __module__ = 'rpc_useragent.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsUserAgentsRequest)
  ))
_sym_db.RegisterMessage(UtilsUserAgentsRequest)

UtilsUserAgentsResponse = _reflection.GeneratedProtocolMessageType('UtilsUserAgentsResponse', (_message.Message,), dict(
  DESCRIPTOR = _UTILSUSERAGENTSRESPONSE,
  __module__ = 'rpc_useragent.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsUserAgentsResponse)
  ))
_sym_db.RegisterMessage(UtilsUserAgentsResponse)

UtilsUserAgentsGroupNamesRequest = _reflection.GeneratedProtocolMessageType('UtilsUserAgentsGroupNamesRequest', (_message.Message,), dict(
  DESCRIPTOR = _UTILSUSERAGENTSGROUPNAMESREQUEST,
  __module__ = 'rpc_useragent.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsUserAgentsGroupNamesRequest)
  ))
_sym_db.RegisterMessage(UtilsUserAgentsGroupNamesRequest)

UtilsUserAgentsGroupNamesResponse = _reflection.GeneratedProtocolMessageType('UtilsUserAgentsGroupNamesResponse', (_message.Message,), dict(
  DESCRIPTOR = _UTILSUSERAGENTSGROUPNAMESRESPONSE,
  __module__ = 'rpc_useragent.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsUserAgentsGroupNamesResponse)
  ))
_sym_db.RegisterMessage(UtilsUserAgentsGroupNamesResponse)

UtilsUserAgentsGroupsRequest = _reflection.GeneratedProtocolMessageType('UtilsUserAgentsGroupsRequest', (_message.Message,), dict(
  DESCRIPTOR = _UTILSUSERAGENTSGROUPSREQUEST,
  __module__ = 'rpc_useragent.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsUserAgentsGroupsRequest)
  ))
_sym_db.RegisterMessage(UtilsUserAgentsGroupsRequest)

UtilsUserAgentsGroupsResponse = _reflection.GeneratedProtocolMessageType('UtilsUserAgentsGroupsResponse', (_message.Message,), dict(
  DESCRIPTOR = _UTILSUSERAGENTSGROUPSRESPONSE,
  __module__ = 'rpc_useragent.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsUserAgentsGroupsResponse)
  ))
_sym_db.RegisterMessage(UtilsUserAgentsGroupsResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
