# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-welcome.auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16rpc-welcome.auth.proto\x12\x04\x61uth\"\x14\n\x12\x41uthWelcomeRequest\"&\n\x13\x41uthWelcomeResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB\x1fZ\x1dgithub.com/sirjager/rpcs/authb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_welcome.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035github.com/sirjager/rpcs/auth'
  _AUTHWELCOMEREQUEST._serialized_start=32
  _AUTHWELCOMEREQUEST._serialized_end=52
  _AUTHWELCOMERESPONSE._serialized_start=54
  _AUTHWELCOMERESPONSE._serialized_end=92
# @@protoc_insertion_point(module_scope)
