# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-welcome.auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc-welcome.auth.proto',
  package='auth',
  syntax='proto3',
  serialized_options=_b('Z\035github.com/sirjager/rpcs/auth'),
  serialized_pb=_b('\n\x16rpc-welcome.auth.proto\x12\x04\x61uth\"\x14\n\x12\x41uthWelcomeRequest\"&\n\x13\x41uthWelcomeResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB\x1fZ\x1dgithub.com/sirjager/rpcs/authb\x06proto3')
)




_AUTHWELCOMEREQUEST = _descriptor.Descriptor(
  name='AuthWelcomeRequest',
  full_name='auth.AuthWelcomeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=52,
)


_AUTHWELCOMERESPONSE = _descriptor.Descriptor(
  name='AuthWelcomeResponse',
  full_name='auth.AuthWelcomeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='auth.AuthWelcomeResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['AuthWelcomeRequest'] = _AUTHWELCOMEREQUEST
DESCRIPTOR.message_types_by_name['AuthWelcomeResponse'] = _AUTHWELCOMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthWelcomeRequest = _reflection.GeneratedProtocolMessageType('AuthWelcomeRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHWELCOMEREQUEST,
  __module__ = 'rpc_welcome.auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.AuthWelcomeRequest)
  ))
_sym_db.RegisterMessage(AuthWelcomeRequest)

AuthWelcomeResponse = _reflection.GeneratedProtocolMessageType('AuthWelcomeResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHWELCOMERESPONSE,
  __module__ = 'rpc_welcome.auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.AuthWelcomeResponse)
  ))
_sym_db.RegisterMessage(AuthWelcomeResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
