# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-forgot.auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rpc-forgot.auth.proto\x12\x04\x61uth\"*\n\x19\x41uthForgotPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"-\n\x1a\x41uthForgotPasswordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"h\n\x18\x41uthResetPasswordRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\x12\x19\n\x11logout_everywhere\x18\x04 \x01(\x08\",\n\x19\x41uthResetPasswordResponse\x12\x0f\n\x07message\x18\x01 \x01(\tB\x1fZ\x1dgithub.com/sirjager/rpcs/authb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_forgot.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035github.com/sirjager/rpcs/auth'
  _AUTHFORGOTPASSWORDREQUEST._serialized_start=31
  _AUTHFORGOTPASSWORDREQUEST._serialized_end=73
  _AUTHFORGOTPASSWORDRESPONSE._serialized_start=75
  _AUTHFORGOTPASSWORDRESPONSE._serialized_end=120
  _AUTHRESETPASSWORDREQUEST._serialized_start=122
  _AUTHRESETPASSWORDREQUEST._serialized_end=226
  _AUTHRESETPASSWORDRESPONSE._serialized_start=228
  _AUTHRESETPASSWORDRESPONSE._serialized_end=272
# @@protoc_insertion_point(module_scope)
