# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc-health.utils.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc-health.utils.proto',
  package='utils',
  syntax='proto3',
  serialized_options=_b('Z\036github.com/sirjager/rpcs/utils'),
  serialized_pb=_b('\n\x16rpc-health.utils.proto\x12\x05utils\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x14\n\x12UtilsHealthRequest\"\xac\x01\n\x13UtilsHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12)\n\x06uptime\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12+\n\x07started\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB Z\x1egithub.com/sirjager/rpcs/utilsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_UTILSHEALTHREQUEST = _descriptor.Descriptor(
  name='UtilsHealthRequest',
  full_name='utils.UtilsHealthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=118,
)


_UTILSHEALTHRESPONSE = _descriptor.Descriptor(
  name='UtilsHealthResponse',
  full_name='utils.UtilsHealthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='utils.UtilsHealthResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='utils.UtilsHealthResponse.uptime', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='started', full_name='utils.UtilsHealthResponse.started', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='utils.UtilsHealthResponse.timestamp', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=293,
)

_UTILSHEALTHRESPONSE.fields_by_name['uptime'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_UTILSHEALTHRESPONSE.fields_by_name['started'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_UTILSHEALTHRESPONSE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UtilsHealthRequest'] = _UTILSHEALTHREQUEST
DESCRIPTOR.message_types_by_name['UtilsHealthResponse'] = _UTILSHEALTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UtilsHealthRequest = _reflection.GeneratedProtocolMessageType('UtilsHealthRequest', (_message.Message,), dict(
  DESCRIPTOR = _UTILSHEALTHREQUEST,
  __module__ = 'rpc_health.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsHealthRequest)
  ))
_sym_db.RegisterMessage(UtilsHealthRequest)

UtilsHealthResponse = _reflection.GeneratedProtocolMessageType('UtilsHealthResponse', (_message.Message,), dict(
  DESCRIPTOR = _UTILSHEALTHRESPONSE,
  __module__ = 'rpc_health.utils_pb2'
  # @@protoc_insertion_point(class_scope:utils.UtilsHealthResponse)
  ))
_sym_db.RegisterMessage(UtilsHealthResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
